<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>v5_core_bridge</name>
  <version>0.0.1</version>
  <description>The IT/OT Bridge Node for V5.1 Mixed-Criticality System</description>
  <maintainer email="architect@todo.todo">V5 Architect</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>v5_interfaces</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
